// Code generated by "go-jason-gen"; DO NOT EDIT.

package sample

import (
	"errors"

	gojason "github.com/isaac-weisberg/go-jason"
)
func makeAddMoneyRequestFromJson(object *gojason.JsonValueObject) (*addMoneyRequest, error) {
}
